### ISSUE TITLE
bump-my-version doesn't work with pydantic >= 2.0

### ISSUE THREAD

**Issue by samongoose** [callowayproject/bump-my-version#32]
* bump-my-version version: 0.6.0
* Python version: 3.11.2
* Operating System: macOS 13.4

### Description

On a fresh `pip install`, all bump-my-version CLI commands fail due to a change in pydantic 2.0, which is installed by default: https://docs.pydantic.dev/latest/migration/#basesettings-has-moved-to-pydantic-settings.  For now, looks like bump-my-version should pin pydantic to < 2.0.

### What I Did

```
>> python3 -m venv venv
>> source venv/bin/activate
(venv) >> pip install bump-my-version
(venv) >> bump-my-version --version
Traceback (most recent call last):
  File "./venv/bin/bump-my-version", line 5, in <module>
    from bumpversion.cli import cli
  File "./venv/lib/python3.11/site-packages/bumpversion/cli.py", line 10, in <module>
    from bumpversion.bump import do_bump
  File "./venv/lib/python3.11/site-packages/bumpversion/bump.py", line 11, in <module>
    from bumpversion.config import Config, update_config_file
  File "./venv/lib/python3.11/site-packages/bumpversion/config.py", line 17, in <module>
    from pydantic import BaseModel, BaseSettings, Field
  File "./venv/lib/python3.11/site-packages/pydantic/__init__.py", line 206, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/pydantic/_migration.py", line 279, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0.1/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.0.1/u/import-error
```

**Comment by jxyyz** [comment]
If anyone is searching for a workaround before the package is updated:
- in your project, manually add `pydantic<2.0` into `requirement.txt` or `requirements.in` (if you're using `pip-tools`)
---- 
 
Basically, it is the solution indicated by @samongoose, but I'm pointing the specific action you need to perform to make it work

**Comment by coordt** [comment]
#30 Will fix this. Should get this merged today
