### ISSUE TITLE
tomlkit cannot parse escaped parentheses

### ISSUE THREAD

**Issue by ichrysou** [callowayproject/bump-my-version#44]
* bump-my-version version: 0.9.2
* Python version: 3.10.12
* Operating System: Linux

### Description

I am trying to search and replace a version macro that looks like this:
`search = "#define EDGE_COM_VERSION_MAJOR (0x{current_version})"
replace = "#define EDGE_COM_VERSION_MAJOR (0x{new_version})"`
Worked fine till regex came in, which is fine given that we have a --no-regex flag.
However toml parser doesn't like the escaped parens of my search string somehow.

### What I Did
 I get this kind of error:
```
⚡ bump-my-version bump minor --allow-dirty
Traceback (most recent call last):
  File "/usr/local/bin/bump-my-version", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bumpversion/cli.py", line 283, in bump
    config = get_configuration(found_config_file, **overrides)
  File "/usr/local/lib/python3.10/dist-packages/bumpversion/config.py", line 145, in get_configuration
    parsed_config = read_config_file(config_file) if config_file else {}
  File "/usr/local/lib/python3.10/dist-packages/bumpversion/config.py", line 262, in read_config_file
    return read_toml_file(config_path)
  File "/usr/local/lib/python3.10/dist-packages/bumpversion/config.py", line 342, in read_toml_file
    toml_data = tomlkit.parse(file_path.read_text()).unwrap()
  File "/usr/local/lib/python3.10/dist-packages/tomlkit/api.py", line 86, in parse
    return Parser(string).parse()
  File "/usr/local/lib/python3.10/dist-packages/tomlkit/parser.py", line 154, in parse
    key, value = self._parse_table()
  File "/usr/local/lib/python3.10/dist-packages/tomlkit/parser.py", line 1012, in _parse_table
    key_next, table_next = self._parse_table(full_key, table)
  File "/usr/local/lib/python3.10/dist-packages/tomlkit/parser.py", line 1038, in _parse_table
    result = self._parse_aot(result, full_key)
  File "/usr/local/lib/python3.10/dist-packages/tomlkit/parser.py", line 1079, in _parse_aot
    _, table = self._parse_table(name_first)
  File "/usr/local/lib/python3.10/dist-packages/tomlkit/parser.py", line 1002, in _parse_table
    item = self._parse_item()
  File "/usr/local/lib/python3.10/dist-packages/tomlkit/parser.py", line 238, in _parse_item
    return self._parse_key_value(True)
  File "/usr/local/lib/python3.10/dist-packages/tomlkit/parser.py", line 331, in _parse_key_value
    val = self._parse_value()
  File "/usr/local/lib/python3.10/dist-packages/tomlkit/parser.py", line 427, in _parse_value
    return self._parse_basic_string()
  File "/usr/local/lib/python3.10/dist-packages/tomlkit/parser.py", line 727, in _parse_basic_string
    return self._parse_string(StringType.SLB)
  File "/usr/local/lib/python3.10/dist-packages/tomlkit/parser.py", line 869, in _parse_string
    value += self._parse_escaped_char(delim.is_multiline())
  File "/usr/local/lib/python3.10/dist-packages/tomlkit/parser.py", line 772, in _parse_escaped_char
    raise self.parse_error(InvalidCharInStringError, self._current)
tomlkit.exceptions.InvalidCharInStringError: Invalid character '(' in string at line 28 col 42

```

**Comment by ichrysou** [comment]
My bad.. I was escaping the parens manually in the search string. 
Closing the issue now.
Also, the --no-regex option works :)

**Comment by ichrysou** [comment]
My bad.. I was escaping the parens manually in the search string.
Closing the issue now.
Also, the --no-regex option works :)
