### ISSUE TITLE
Serialization fails if first match is not found

### ISSUE THREAD

**Issue by skipperTux** [callowayproject/bump-my-version#75]
* bump-my-version version: 0.11.0
* Python version: 3.12.0
* Operating System: MS Windows 11 Enterprise

### Description

With regards to Issue #45 - already closed (and Issue #74). As [you said](https://github.com/callowayproject/bump-my-version/issues/45#issuecomment-1680592339) the order is top-down (first to last) and the first successful serialization is chosen. 

Having a config serialization like

```
"{major};{minor};{patch};;build.{build}",
"{major};{minor};{patch};{release};build.{build}"
```

I would expect these two patterns work as follows, first pattern is used for a match in the file. If no match is found, the second pattern is used for matching. However the second serialization pattern is never used, an error is given for the first pattern not matching.

When switching the order of the patterns, this first case is working. However a second case, when there is no 'release'-part in the current version, is not working. Now 'final' is expected in the match, although defined as `optional_value`. Again only the first pattern is matched.

See all examples and configs below.

(This setup works successfully with [ADVbumpversion](https://github.com/andrivet/ADVbumpversion) - as we are still running that fork -, using the switched order of serialization patterns.)

### What I Did

`.bumpversion.toml` (excerpt with relevant file part for this issue).

```
[tool.bumpversion]
current_version = "app/3.5.0-beta+build.1038"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(-(?P<release>[0-9A-Za-z]+))?(\\+build\\.(?P<build>.[0-9A-Za-z]+))?"
serialize = [
	"{major}.{minor}.{patch}+build.{build}",
	"{major}.{minor}.{patch}-{release}+build.{build}"
]
commit = true
message = "Bump version: {current_version} -> {new_version}"
tag = false
tag_name = "app/{new_version}"
tag_message = "Version app/{new_version}"
allow_dirty = true

[tool.bumpversion.parts.release]
values = [
	"beta",
	"rc",
	"final"
]
optional_value = "final"

[tool.bumpversion.parts.build]
first_value = 1000
independent = true


[[tool.bumpversion.files]]
filename = "..\\SqlScripts\\Import\\Version.csv"
parse = "(?P<major>\\d+);(?P<minor>\\d+);(?P<patch>\\d+);(?P<release>[0-9A-Za-z]+)?;(build\\.(?P<build>.[0-9A-Za-z]+))?"
serialize = [
	"{major};{minor};{patch};;build.{build}",
	"{major};{minor};{patch};{release};build.{build}"
]
search = "1;{current_version}"
replace = "1;{new_version}"
```

File `Version.csv`
```
Id;Major;Minor;Patch;Release;Metadata
1;3;5;0;beta;build.1038
```

```
$ bump-my-version.exe bump -vvv --tag --no-commit patch
Starting BumpVersion 0.11.0
Reading config file .bumpversion.toml:
Parsing version 'app/3.5.0-beta+build.1038' using regexp
'(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(-(?P<release>[0-9A-Za-z]+))?(\+build\.(?P<build>.[0-9A-Za-z]+))?'
Parsed the following values: build=1038, major=3, minor=5, patch=0, release=beta
Attempting to increment part 'patch'
Values are now: build=1038, major=3, minor=5, patch=1, release=beta
Available serialization formats: '{major}.{minor}.{patch}-{release}+build.{build}',
'{major}.{minor}.{patch}+build.{build}'
Found '{major}.{minor}.{patch}-{release}+build.{build}' to be a usable serialization format
Selected serialization format '{major}.{minor}.{patch}-{release}+build.{build}'
Serialized to '3.5.1-beta+build.1038'
New version will be '3.5.1-beta+build.1038'
Asserting files ..\SqlScripts\Import\Version.csv contain the version string...
Available serialization formats: '{major};{minor};{patch};;build.{build}',
'{major};{minor};{patch};{release};build.{build}'
Found '{major};{minor};{patch};;build.{build}' to be a usable serialization format
Found '{major};{minor};{patch};{release};build.{build}' usable serialization format, but it's longer
Selected serialization format '{major};{minor};{patch};;build.{build}'
Serialized to '3;5;0;;build.1038'
Searching for the regex: '1;3;5;0;;build\.1038'

 Usage: bump-my-version bump [OPTIONS] [ARGS]...

 Try 'bump-my-version bump --help' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Did not find '1;3;5;0;;build\.1038' in file: '..\SqlScripts\Import\Version.csv'                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

#### Switching the order of serialization patterns

```
    "{major}.{minor}.{patch}-{release}+build.{build}",
    "{major}.{minor}.{patch}+build.{build}"
```

File `Version.csv`
```
Id;Major;Minor;Patch;Release;Metadata
1;3;5;0;;build.1038
```

```
$ bump-my-version.exe bump -vvv --tag --no-commit major
Starting BumpVersion 0.11.0
Reading config file .bumpversion.toml:
Specified version (app/3.5.0+build.1038) does not match last tagged version (app/3.5.0-beta+build.1038) // see issue #74
Parsing version 'app/3.5.0+build.1038' using regexp
'(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(-(?P<release>[0-9A-Za-z]+))?(\+build\.(?P<build>.[0-9A-Za-z]+))?'
Parsed the following values: build=1038, major=3, minor=5, patch=0, release=final
Attempting to increment part 'major'
Values are now: build=1038, major=4, minor=0, patch=0, release=beta
Available serialization formats: '{major}.{minor}.{patch}-{release}+build.{build}',
'{major}.{minor}.{patch}+build.{build}'
Found '{major}.{minor}.{patch}-{release}+build.{build}' to be a usable serialization format
Selected serialization format '{major}.{minor}.{patch}-{release}+build.{build}'
Serialized to '4.0.0-beta+build.1038'
New version will be '4.0.0-beta+build.1038'
Asserting files ..\SqlScripts\Import\Version.csv contain the version string...
Available serialization formats: '{major};{minor};{patch};{release};build.{build}',
'{major};{minor};{patch};;build.{build}'
Found '{major};{minor};{patch};{release};build.{build}' to be a usable serialization format
Selected serialization format '{major};{minor};{patch};{release};build.{build}'
Serialized to '3;5;0;final;build.1038'
Searching for the regex: '1;3;5;0;final;build\.1038'

 Usage: bump-my-version bump [OPTIONS] [ARGS]...

 Try 'bump-my-version bump --help' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Did not find '1;3;5;0;final;build\.1038' in file: '..\SqlScripts\Import\Version.csv'           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

###### Edit: Path corrections

**Comment by coordt** [comment]
You might try adding the `ignore_missing_version` setting: https://callowayproject.github.io/bump-my-version/reference/configuration.html#ignore-missing-version

See if that fixes your issue.

**Comment by skipperTux** [comment]
I added `ignore-missing-version = true` to the chapter `[tool.bumpversion]`, but it does not fix the issue. Depending on the current version and order of the serialization patterns the error is either not expecting the `beta` or expecting the `final`, just like before.

It also seems like the configuration `optional_value` is not working as before, when bumping `build` the resulting  version is `app/3.5.0-final+build.1039`, but it should be `app/3.5.0+build.1039`.

**Comment by coordt** [comment]
@skipperTux Can you check with the latest version to see if this is still happening. I've refactored the versioning and serialization logic to make it easier to test.

**Comment by skipperTux** [comment]
Ha ha, what a coincidence. I did prepare a [MCVE-project](https://idownvotedbecau.se/nomcve/) last week, but did not find the time to post my results.

I just tested `BumpVersion 0.17.3` with my project and this issues is resolved, bumping major, minor, patch, release or build does work as expected. I removed `ignore-missing-version = true` from the config and the test continues to work as expected. That option might not be necessary for this situation.

Minor remark, when calling `bump-my-version.exe bump -v --no-tag --no-commit release` three times, I end up getting the expected message `ValueError: The part has already the maximum value among ['beta', 'rc', 'final'] and cannot be bumped.` but prefaced by an exception.

<details>
<summary>Exception (IndexError)</summary>

Starting BumpVersion 0.17.3
Reading configuration
  Reading config file: C:\Users\christoph\source\repos\BumpVersionMCVE\\.bumpversion.toml
  Parsing current version '6.4.4+build.1050'
  Attempting to increment part 'release'
Traceback (most recent call last):
  File "C:\Users\christoph\AppData\Roaming\Python\Python312\site-packages\bumpversion\versioning\functions.py", line 124, in bump
    return self._values[self._values.index(value) + 1]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\christoph\AppData\Roaming\Python\Python312\Scripts\bump-my-version.exe\__main__.py", line 7, in <module>
  File "C:\Users\christoph\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\christoph\AppData\Roaming\Python\Python312\site-packages\rich_click\rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\christoph\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\christoph\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\christoph\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\christoph\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\christoph\AppData\Roaming\Python\Python312\site-packages\bumpversion\cli.py", line 315, in bump
    do_bump(version_part, new_version, config, found_config_file, dry_run)
  File "C:\Users\christoph\AppData\Roaming\Python\Python312\site-packages\bumpversion\bump.py", line 80, in do_bump
    next_version = get_next_version(version, config, version_part, new_version)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\christoph\AppData\Roaming\Python\Python312\site-packages\bumpversion\bump.py", line 45, in get_next_version
    next_version = current_version.bump(version_part)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\christoph\AppData\Roaming\Python\Python312\site-packages\bumpversion\versioning\models.py", line 214, in bump
    new_values[component_name] = self.components[component_name].bump()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\christoph\AppData\Roaming\Python\Python312\site-packages\bumpversion\versioning\models.py", line 62, in bump
    new_component._value = self.func.bump(self.value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\christoph\AppData\Roaming\Python\Python312\site-packages\bumpversion\versioning\functions.py", line 126, in bump
    raise ValueError(
ValueError: The part has already the maximum value among ['beta', 'rc', 'final'] and cannot be bumped.
</details>

Thanks for your perseverance in fixing this error :+1:. Case closed.
