### ISSUE TITLE
Support multi-line search patterns

### ISSUE THREAD

**Issue by cortlepp-intershop** [callowayproject/bump-my-version#79]
* bump-my-version version: 0.11.0
* Python version: 3.10.12
* Operating System: Ubuntu 22.04 LTS

### Description

This is more of a question, than a problem: I am trying to use bump-my-version to automate versioning for helm-charts. The files I want to bump look like this:

```yaml
apiVersion: v2
appVersion: "11.2.1"
description: Intershop Commerce Management - ICM
# name and version must be in this exact order, otherwise bump2version won't work
name: icm
version: 1.4.0
# test related annotations
annotations:
  requestedMemoryQuota: 5900Mi
  requestedCpuQuotaInMinutes: "2500"
dependencies:
  - name: icm-as
    version: 1.3.0
    repository: file://../icm-as
  - name: icm-web
    version: 0.8.0
    repository: file://../icm-web
    condition: icm-web.enabled
  - name: mailhog
    version: 5.2.0
    repository: https://codecentric.github.io/helm-charts
    condition: mailhog.enabled
  - name: redis
    version: 17.15.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: redis-cluster
    version: 8.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: redis-cluster.enabled

```
Note that there are many versions in this file, and using search/replace I can't simply look for the version, instead I also need to take the name as "context". Additionally, a single version may affect multiple files since we have multiple subcharts which depend on each other.

I was trying to achieve this behavior with this `.bumpversion.cfg` file in bump2version:

```
[bumpversion]
current_version = 1.4.0

[bumpversion:file:Chart.yaml]
search = name: icm
	version: {current_version}
replace = {new_version}

[bumpversion:file:../icm-replication/Chart.yaml]
search = name: icm
	version: {current_version}
replace = {new_version}
```

This didn't work though, because for some reason bump2version treats the first search pattern differently than the second (for the first pattern it replaces the whole search with the new version, in the second pattern only the {current_version} part).
When I tried this config with bump-my-version I simply got an error:

```
Bumping version of 'icm-as' to next 'minor' value.
Could not execute version bump.
Return code 1
STDERR:
Traceback (most recent call last):
  File "/home/cortlepp/.local/bin/bump-my-version", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/cortlepp/.local/lib/python3.10/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/cortlepp/.local/lib/python3.10/site-packages/bumpversion/cli.py", line 283, in bump
    config = get_configuration(found_config_file, **overrides)
  File "/home/cortlepp/.local/lib/python3.10/site-packages/bumpversion/config.py", line 194, in get_configuration
    config_dict["files"] = get_all_file_configs(config_dict)
  File "/home/cortlepp/.local/lib/python3.10/site-packages/bumpversion/config.py", line 165, in get_all_file_configs
    return [FileConfig(**f) for f in files]
  File "/home/cortlepp/.local/lib/python3.10/site-packages/bumpversion/config.py", line 165, in <listcomp>
    return [FileConfig(**f) for f in files]
  File "/home/cortlepp/.local/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for FileConfig
search
  Input should be a valid string [type=string_type, input_value=['name: icm-as', 'version: {current_version}'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type

STDOUT:

WARNING:

Calling bumpversion without a subcommand is deprecated. Please use `bumpversion bump` instead


WARNING:

The .cfg file format is deprecated. Please use .toml instead.
```

Now my question: Can I get this to work with bump-my-version (and if so, how)? I couldn't find any information on how to match more than the simple version in your repo.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by khauser** [comment]
```
[bumpversion]
current_version = 1.4.0

# note: the indent after "search" is required to signal bump2version that the pattern continues
[bumpversion:file:Chart.yaml]
search = name: icm
	version: {current_version}
replace = name: icm
	version: {new_version}

[bumpversion:file:../icm-replication/Chart.yaml]
search = name: icm
	version: {current_version}
replace = {new_version}
```
We were able to fix our issue with the above cfg. Hopefully this multi-line-search-pattern feature will also work with .toml.

**Comment by coordt** [comment]
The [search and replace docs](https://callowayproject.github.io/bump-my-version/reference/search-and-replace-config.html) demonstrate multi-line behavior.

The issues with indenting and type-checking is one of the reasons we deprecated `.cfg` files. They are tricky to get right.
